import './globals.css'
import { Nunito } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Root Acadmey',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  )
}
